# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "yard-rest"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["R. Kevin Nelson", "Aisha Fenton", "Sebastian Pape"]
  s.date = "2012-04-30"
  s.description = "A customized plugin for Yardoc that produces API documentation for Restful web services"
  s.email = ""
  s.extra_rdoc_files = [
    "README.markdown",
    "VERSION"
  ]
  s.files = [
    "Rakefile",
    "example/app/controllers/examples_controller.rb",
    "lib/yard-rest.rb",
    "lib/yard-rest/rest_filters.rb",
    "lib/yard-rest/tags.rb"
  ]
  s.homepage = "https://github.com/spape/yard-rest-plugin"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "A customized plugin for Yardoc that produces API documentation for Restful web services"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yard>, ["~> 0.7.4"])
    else
      s.add_dependency(%q<yard>, ["~> 0.7.4"])
    end
  else
    s.add_dependency(%q<yard>, ["~> 0.7.4"])
  end
end

