# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "yard-rest"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["R. Kevin Nelson", "Aisha Fenton", "Sebastian Pape"]
  s.date = "2012-04-30"
  s.description = "A customized plugin for Yardoc that produces API documentation for Restful web services"
  s.email = ""
  s.extra_rdoc_files = [
    "README.markdown",
    "VERSION"
  ]
  s.files = [
    "Rakefile",
    "example/app/controllers/examples_controller.rb",
    "example/doc/README_FOR_API",
    "lib/yard-rest.rb",
    "lib/yard-rest/rest_filters.rb",
    "lib/yard-rest/tags.rb",
    "templates/rest/class/html/header.erb",
    "templates/rest/class/html/method_details_list.erb",
    "templates/rest/class/html/setup.rb",
    "templates/rest/docstring/html/setup.rb",
    "templates/rest/docstring/html/text.erb",
    "templates/rest/fulldoc/html/full_list_resource.erb",
    "templates/rest/fulldoc/html/full_list_topic.erb",
    "templates/rest/fulldoc/html/js/rest_plugin.js",
    "templates/rest/fulldoc/html/setup.rb",
    "templates/rest/layout/html/footer.erb",
    "templates/rest/layout/html/index.erb",
    "templates/rest/layout/html/layout.erb",
    "templates/rest/layout/html/search.erb",
    "templates/rest/layout/html/setup.rb",
    "templates/rest/method_details/html/header.erb",
    "templates/rest/method_details/html/method_url.erb",
    "templates/rest/method_details/html/setup.rb",
    "templates/rest/tags/html/example_request.erb",
    "templates/rest/tags/html/example_response.erb",
    "templates/rest/tags/html/generic_tag.erb",
    "templates/rest/tags/html/index.erb",
    "templates/rest/tags/html/key_for.erb",
    "templates/rest/tags/html/value_for.erb",
    "templates/rest/tags/setup.rb"
  ]
  s.homepage = "https://github.com/spape/yard-rest-plugin"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "A customized plugin for Yardoc that produces API documentation for Restful web services"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yard>, ["~> 0.7.4"])
    else
      s.add_dependency(%q<yard>, ["~> 0.7.4"])
    end
  else
    s.add_dependency(%q<yard>, ["~> 0.7.4"])
  end
end

